### ISSUE TITLE
Stylesheet doesn't work

### ISSUE THREAD

**Issue by lepicekmichal** [NetCZ/vue-separate-files-webpack-loader-example#5]
I have a project with components folder containing:

- UserList.vue.pug
- UserList.vue.ts
- UserList.vue.scss

Your plugin generates 

```
<template separated src="ABSOLUTE_PATH/UserList.vue.pug" lang="pug"></template>
<script separated src="ABSOLUTE_PATH/UserList.vue.ts" lang="ts"></script>
<style separated src="ABSOLUTE_PATH/UserList.vue.scoped.scss" scoped lang="scss"></style>
```

If I remove separated attribute and put in relative path instead of absolute, I get a fully functional Vue file. However, whatever I do (including nothing), style does not get applied in the final result. Never. Website is always without any css style.

I am using vue.config.js example from your readme and project was generated by vue-cli 4.

Can you check what does vue-loader need in terms of css tag (and fix it :smile:)? Thank you!

**Comment by NetCZ** [comment]
Hi @lepicekmichal, thanks for reporting the issue. Unfortunately I'm very busy on other projects and can't promise any quick fixes. But feel free to create PR.

**Comment by lepicekmichal** [comment]
I tried to fix it with no solution. I will definitely try again if you find few minutes to share me some pointers, resources or any other helpful knowledge.

**Comment by lepicekmichal** [comment]
**Update**
When I rename .ts file to .js (and do few content adjustments), stylesheet suddenly works.
So seems like vue-loader has some problem with typescript

**Comment by NetCZ** [comment]
Hi @lepicekmichal, I got back to this issue and it seems like either issue with `vue-loader` (but I doubt it) or your webpack configuration. You said you removed "separated" tag from generated files, but those files are not written to disk, so it looks like you're doing some manual interception of the files. Can you perhaps link some example repo, its hard to find out what's the issue.
